Repository opensource-together/opensource-together, pull requests merged in 2025-07, with the labels that each got.

#268 Bug sur l'input recherche du composant combobox
  apps/web/src/shared/components/ui/combobox.tsx
Labels: bug, Frontend

#280 Y2/dashboard layout styling
  apps/web/src/app/collaboration/layout.tsx
  apps/web/src/app/collaboration/page.tsx
  apps/web/src/features/collaboration/components/collaboration-sidebar.component.tsx
  apps/web/src/features/projects/components/project-discovery-hero.component.tsx
  apps/web/src/features/projects/views/homepage.view.tsx
  apps/web/src/shared/components/layout/footer.tsx
  apps/web/src/shared/components/layout/header.tsx
Labels: Design

#303 chore(main): release 0.1.4
  .github/release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#305 chore(main): release 0.1.5
  .github/release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#316 chore(main): release 0.1.10
  .github/release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#368 chore: release v0.2.0
  .github/release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending
