Repository opensource-together/opensource-together, pull requests merged in 2025-05, with the labels that each got.

#113 Ajouts de 4 ends points dont 3 GET et 1 POST part2
  .cursor/rules/backend_architecture.mdc
  apps/server/package.json
  apps/server/pnpm-lock.yaml
  apps/server/src/app.module.ts
  apps/server/src/application/dto/adapters/project-response.adapter.ts
  apps/server/src/application/dto/adapters/project-response.dto.ts
  apps/server/src/application/dto/inputs/create-project-inputs.dto.ts
  apps/server/src/application/dto/inputs/create-user-input.dto.ts
  apps/server/src/application/ports/project.repository.port.ts
  apps/server/src/application/use-cases/create-project.usecase.spec.ts
  apps/server/src/application/use-cases/create-project.usecase.ts
  apps/server/src/application/use-cases/create-user.usecase.ts
  apps/server/src/domain/project/ProjectTestBuilder.ts
  apps/server/src/domain/project/description/description.vo.spec.ts
  apps/server/src/domain/project/description/description.vo.ts
  apps/server/src/domain/project/factory/project.factory.spec.ts
  apps/server/src/domain/project/factory/project.factory.ts
  apps/server/src/domain/project/link/link.vo.spec.ts
  apps/server/src/domain/project/link/link.vo.ts
  apps/server/src/domain/project/project.entity.spec.ts
  apps/server/src/domain/project/project.entity.ts
  apps/server/src/domain/project/status/status.vo.spec.ts
  apps/server/src/domain/project/status/status.vo.ts
  apps/server/src/domain/project/title/title.vo.spec.ts
  apps/server/src/domain/project/title/title.vo.ts
  apps/server/src/domain/techStack/techStack.factory.ts
  apps/server/src/domain/techStack/techstack.entity.spec.ts
  apps/server/src/domain/techStack/techstack.entity.ts
  apps/server/src/infrastructures/auth/recipes/email-password.recipe.ts
  apps/server/src/infrastructures/cqrs/cqrs-wiring.module.ts
  apps/server/src/infrastructures/cqrs/project/commands/create-project/create-project.command.ts
  apps/server/src/infrastructures/cqrs/project/commands/create-project/create-project.handler.ts
  apps/server/src/infrastructures/cqrs/project/project-cqrs.module.ts
  apps/server/src/infrastructures/cqrs/project/queries/find-by-id/find-project-by-id.handler.ts
  apps/server/src/infrastructures/cqrs/project/queries/find-by-id/find-project-by-id.query.ts
  apps/server/src/infrastructures/cqrs/project/queries/find-by-title/find-project-by-title.handler.ts
  apps/server/src/infrastructures/cqrs/project/queries/find-by-title/find-project-by-title.query.ts
  apps/server/src/infrastructures/cqrs/project/queries/get-all/get-projects.handler.ts
  apps/server/src/infrastructures/cqrs/project/queries/get-all/get-projects.query.ts
  apps/server/src/infrastructures/cqrs/user/user-cqrs.module.ts
  apps/server/src/infrastructures/orm/prisma/migrations/20250418113203_init/migration.sql
  apps/server/src/infrastructures/orm/prisma/migrations/migration_lock.toml
  apps/server/src/infrastructures/orm/prisma/prisma.service.ts
  apps/server/src/infrastructures/orm/prisma/schema.prisma
  apps/server/src/infrastructures/repositories/__tests__/PrismaMock.ts
  apps/server/src/infrastructures/repositories/prisma.project.repository.spec.ts
  apps/server/src/infrastructures/repositories/prisma.project.repository.ts
  apps/server/src/infrastructures/repositories/project/prisma.project.mapper.ts
  apps/server/src/presentation/present.module.ts
  apps/server/src/presentation/project/dto/CreateaProjectDtoRequest.ts
  apps/server/src/presentation/project/dto/TechStackDto.request.ts
  apps/server/src/presentation/project/project.controller.ts
  apps/server/src/presentation/project/project.module.ts
  apps/server/src/shared/__test__/ProjectTestBuilder.ts
  apps/server/src/shared/__test__/TechStackTestBuilder.ts
  apps/server/src/shared/test-utils.ts
Labels: Backend

#127 Résumé de la branche feature/frontend-project-detail-page OST-118
  apps/web/src/app/project/page.tsx
  apps/web/src/app/projets/[slug]/page.tsx
  apps/web/src/features/profile/components/ProfileCard.tsx
  apps/web/src/features/profile/components/ProjectCard.tsx
  apps/web/src/features/profile/views/ProfilePageView.tsx
  apps/web/src/features/projects/components/ProjectCard.tsx
  apps/web/src/features/projects/components/ProjectFilters.tsx
  apps/web/src/features/projects/components/ProjectPageCard.tsx
  apps/web/src/features/projects/components/ProjectSideBar.tsx
  apps/web/src/features/projects/components/RoleCard.tsx
  apps/web/src/features/projects/components/SkeletonProjectDetail.tsx
  apps/web/src/features/projects/hooks/useProjects.ts
  apps/web/src/features/projects/services/createProjectAPI.ts
  apps/web/src/features/projects/services/projectAPI.ts
  apps/web/src/features/projects/types/project.ts
  apps/web/src/features/projects/views/HomepageViews.tsx
  apps/web/src/features/projects/views/MyProjectPageView.tsx
  apps/web/src/features/projects/views/ProjectDetailView.tsx
  apps/web/src/shared/icons/Difficulty-bar-gray.svg
  apps/web/src/shared/icons/Difficulty-bar-light.svg
  apps/web/src/shared/icons/pinned-icon.svg
  apps/web/src/shared/icons/validation-icon.svg
  apps/web/src/shared/ui/Breadcrumb.tsx
Labels: Frontend

#149 chore(main): release 0.1.3
  .github/release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#150 chore(main): release 0.1.4
  .github/release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#163 chore(main): release 0.1.1
  .github/release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#166 chore(main): release 0.1.2
  .github/release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending

#168 Commentaire de PR pour OST #119 - Fonctionnalité de création de projet
  apps/web/package-lock.json
  apps/web/package.json
  apps/web/src/app/projects/new/layout.tsx
  apps/web/src/app/projects/new/page.tsx
  apps/web/src/features/projects/components/ProjectForm.tsx
  apps/web/src/features/projects/components/ProjectPageCard.tsx
  apps/web/src/features/projects/components/RoleCard.tsx
  apps/web/src/features/projects/hooks/useProjects.ts
  apps/web/src/features/projects/schema/project.schema.ts
  apps/web/src/features/projects/services/createProjectAPI.ts
  apps/web/src/features/projects/views/ProjectCreateView.tsx
  apps/web/src/shared/layout/Header.tsx
Labels: Frontend, Improvement, View

#171 OST 120 PR Implémentation du formulaire d'édition de projet #123
  apps/web/src/app/projects/[projectId]/edit/page.tsx
  apps/web/src/features/projects/components/ProjectEditForm.tsx
  apps/web/src/features/projects/components/ProjectForm.tsx
  apps/web/src/features/projects/hooks/useProjects.ts
  apps/web/src/features/projects/hooks/useUpdateProject.ts
  apps/web/src/features/projects/schema/project.schema.ts
  apps/web/src/features/projects/services/createProjectAPI.ts
  apps/web/src/features/projects/services/updateProjectAPI.ts
  apps/web/src/features/projects/views/ProjectEditView.tsx
Labels: Frontend, View

#172 Y2/ost 161 refactoriser la logique metier liee aux projets
  apps/web/package-lock.json
  apps/web/package.json
  apps/web/pnpm-lock.yaml
  apps/web/src/app/layout.tsx
  apps/web/src/app/providers.tsx
  apps/web/src/features/profile/views/ProfilePageView.tsx
  apps/web/src/features/projects/components/ProjectEditForm.tsx
  apps/web/src/features/projects/components/ProjectForm.tsx
  apps/web/src/features/projects/components/ProjectPageCard.tsx
  apps/web/src/features/projects/components/ProjectSideBar.tsx
  apps/web/src/features/projects/components/RoleCard.tsx
  apps/web/src/features/projects/data/mockProjects.ts
  apps/web/src/features/projects/hooks/useProjects.ts
  apps/web/src/features/projects/hooks/useUpdateProject.ts
  apps/web/src/features/projects/services/createProjectAPI.ts
  apps/web/src/features/projects/services/projectAPI.ts
  apps/web/src/features/projects/services/updateProjectAPI.ts
  apps/web/src/features/projects/types/ProjectTypes.ts
  apps/web/src/features/projects/views/HomepageViews.tsx
  apps/web/src/features/projects/views/ProjectCreateView.tsx
  apps/web/src/features/projects/views/ProjectDetailView.tsx
  apps/web/src/features/projects/views/ProjectEditView.tsx
  apps/web/src/shared/layout/Header.tsx
Labels: Improvement

#180 Feature/isolate business logic from views OST #168
  apps/web/src/features/projects/components/ProjectDetailContent.tsx
  apps/web/src/features/projects/components/ProjectGrid.tsx
  apps/web/src/features/projects/views/HomepageViews.tsx
  apps/web/src/features/projects/views/ProjectDetailView.tsx
Labels: Frontend, Improvement

#188 Y2/ost 169 creer les services et hooks lies au profil utilisateur
  apps/web/src/app/profile/page.tsx
  apps/web/src/components/ui/project-card.tsx
  apps/web/src/components/ui/skeleton.tsx
  apps/web/src/features/profile/components/PinnedProjects.tsx
  apps/web/src/features/profile/components/ProfileHero.tsx
  apps/web/src/features/profile/components/ProfileSidebar.tsx
  apps/web/src/features/profile/components/error-ui/ProfileError.tsx
  apps/web/src/features/profile/components/skeletons/SkeletonPinnedProjects.tsx
  apps/web/src/features/profile/components/skeletons/SkeletonProfileHero.tsx
  apps/web/src/features/profile/components/skeletons/SkeletonProfilePageView.tsx
  apps/web/src/features/profile/components/skeletons/SkeletonProfileSidebar.tsx
  apps/web/src/features/profile/data/mockProfile.ts
  apps/web/src/features/profile/hooks/useProfile.ts
  apps/web/src/features/profile/services/profileApi.ts
  apps/web/src/features/profile/types/profile.ts
  apps/web/src/features/profile/types/profileTypes.ts
  apps/web/src/features/profile/views/ProfilePageView.tsx
  apps/web/src/features/profile/views/ProfileView.tsx
Labels: Frontend, Improvement

#200 Feature/GitHub auth page
  apps/web/.env.example
  apps/web/public/icons/background-login-page.svg
  apps/web/public/icons/image-login-example.svg
  apps/web/public/icons/ost-logo-login.svg
  apps/web/public/icons/screen-login-page.svg
  apps/web/src/app/auth/login/page.tsx
  apps/web/src/app/auth/signin/page.tsx
  apps/web/src/app/auth/signup/page.tsx
  apps/web/src/app/layout.tsx
  apps/web/src/components/shared/layout/Header.tsx
  apps/web/src/components/ui/button.tsx
  apps/web/src/features/auth/components/AuthCard.tsx
  apps/web/src/features/auth/components/AuthIllustration.tsx
  apps/web/src/features/auth/components/GitHubButton.tsx
  apps/web/src/features/auth/components/LoginForm.tsx
  apps/web/src/features/auth/components/SignUpForm.tsx
  apps/web/src/features/auth/utils/SuperTokensInitializer.tsx
  apps/web/src/features/auth/views/LoginView.tsx
  apps/web/src/features/auth/views/SignUpView.tsx
Labels: Frontend, View
